export const avatar = [
    {id: 1, img: "A", gen: "F"},
    {id: 2, img: "B", gen: "F"},
    {id: 3, img: "C", gen: "M"},
    {id: 4, img: "D", gen: "F"},
    {id: 5, img: "E", gen: "M"},
    {id: 6, img: "F", gen: "F"},
    {id: 7, img: "G", gen: "F"},
    {id: 8, img: "H", gen: "F"},
    {id: 9, img: "I", gen: "F"},
    {id: 10, img: "J", gen: "M"},
    {id: 11, img: "K", gen: "M"},
    {id: 12, img: "L", gen: "F"},
    {id: 13, img: "M", gen: "F"},
    {id: 14, img: "N", gen: "F"},
    {id: 15, img: "O", gen: "F"},
    {id: 16, img: "P", gen: "F"},
    {id: 17, img: "Q", gen: "M"},
    {id: 18, img: "R", gen: "F"},
    {id: 19, img: "S", gen: "F"},
    {id: 20, img: "T", gen: "F"},
    {id: 21, img: "U", gen: "F"},
    {id: 22, img: "V", gen: "F"},
    {id: 23, img: "W", gen: "F"},
    {id: 24, img: "X", gen: "F"},
]

